Roguelike 1
akhvorov/roguelike pull request #2
Opened 2019-04-16 18:56 UTC by akhvorov

Команда: Владислав Танков, Антон Елисеев, Александр Хворов

2019-05-28 16:32 UTC, ottergottaott requested changes
В целом ок, по коду оставил небольшие замечания

Еще нужны unit тесты и комментарии

2019-05-28 16:32 UTC, aleksZubakov commented on src/main/kotlin/com/rogue/actor/enemy/EnemyActor.kt
> +    fun populateMap(levelMap: LevelMap) {
Метод такой же, как и у `Inventories`. При этом у обоих кроме `populateMap` других методов нет, очень напрашивается одна иерархия.

2019-05-28 16:32 UTC, aleksZubakov commented on src/main/kotlin/com/rogue/actor/enemy/EnemyActor.kt
> +object EnemyActor {
Вообще непонятно почему это `EnemyActor`, если тут происходит только инициализация. Кажется, что object для этого излишен.

2019-05-28 16:32 UTC, aleksZubakov commented on src/main/kotlin/com/rogue/actor/enemy/EnemyActor.kt
> +object EnemyActor {
А еще `populateMap` такой же, как и у `Inventories`, напрашивается один интерфейс.

2019-05-28 16:32 UTC, aleksZubakov commented on src/main/kotlin/com/rogue/actor/inventory/Knife.kt
> +        fun random() = Knife(Random.nextInt(1, 5))
Крайне странно, что у `Knife` меняется ID при добавлении в инвентарь.

2019-05-28 16:32 UTC, aleksZubakov commented on src/main/kotlin/com/rogue/map/MazeGenerator.kt
> +    private fun between(v: Int, upper: Int) = v in 0..(upper - 1)
`v in 0 until upper`

2019-05-28 16:32 UTC, aleksZubakov commented on src/main/kotlin/com/rogue/actor/inventory/ArmorActor.kt
> +    fun default() = Actor(Actor.Type.ArmorInventory, Actor.Health(true, 1), 0, 'H')
Аналогично неясно зачем нужен `<Item>Actor`, если в нем только утильный метод для создания соответствующего `Actor`. Лучше сделать один объект с пучком утильных методов, код станет читаемее. Ну или все-таки сделать полноценный полиморфизм, повозившись с сериализацией.

2019-05-28 16:32 UTC, aleksZubakov commented on src/main/kotlin/com/rogue/draw/Application.kt
> +    val menuScreen by lazy { Screens.createScreenFor(ui) }
Можно перенести `menuScreen` и `gameScreen` в соответствующие `MenuScreen` и `GameScreen`

2019-05-28 16:32 UTC, aleksZubakov commented on src/main/kotlin/com/rogue/draw/GameScreen.kt
> +    data class ActorPresentation(val layer: Layer, val tile: CharacterTile)
Было бы также хорошо видеть один интерфейс для `GameScreen` и `MenuScreen`

2019-06-12 14:02 UTC, TanVD commented on src/main/kotlin/com/rogue/actor/inventory/ArmorActor.kt
> +    fun default() = Actor(Actor.Type.ArmorInventory, Actor.Health(true, 1), 0, 'H')
Не хочется очень делать полиморфную десериализацию :) Когда прикручивал её к Jackson и ощущения были самые неприятные, правда не в курсе работает ли это лучше в kotlinx.serialization

2019-06-13 17:57 UTC, aleksZubakov commented
Btw, во втором задании требовалось следующее
_Используя паттерн "Декоратор", реализовать заклинание конфузии, накладываемое на игрока. Игрок, находящийся под эффектом конфузии, перемещается, случайно выбирая направление из трёх, наиболее близких к направлению, выбранному игроком (например, при попытке сделать шаг вверх игрок с равной вероятностью делает шаг вверх, вверх-влево или вверх-вправо). Эффект должен быть временным._

В третьем следующее:
_Переделать взаимодействие с пользователем на паттерн "Команда"_

Не вижу, чтобы это было сделано, поправьте, если ошибаюсь

2019-06-18 19:27 UTC, yurii-litvinov requested changes
При запуске выбираю New Game, оно вроде как долю секунды что-то показывает, потом падает со следующим стектрейсом:
```
Exception in thread "main" java.lang.NoSuchFieldError: level
	at com.rogue.actor.Actor$Stats.<init>(Actor.kt)
	at com.rogue.actor.Actor$Stats$$serializer.deserialize(Actor.kt)
	at com.rogue.actor.Actor$Stats$$serializer.deserialize(Actor.kt:39)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at com.rogue.actor.Actor$$serializer.deserialize(Actor.kt)
	at com.rogue.actor.Actor$$serializer.deserialize(Actor.kt:16)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at com.rogue.map.LevelMap$Cell$$serializer.deserialize(LevelMap.kt)
	at com.rogue.map.LevelMap$Cell$$serializer.deserialize(LevelMap.kt:28)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at kotlinx.serialization.internal.ListLikeSerializer.readItem(CollectionSerializers.kt:98)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readItem$default(CollectionSerializers.kt:70)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:61)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at com.rogue.map.LevelMap$$serializer.deserialize(LevelMap.kt)
	at com.rogue.map.LevelMap$$serializer.deserialize(LevelMap.kt:19)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:33)
	at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:29)
	at kotlinx.serialization.CoreKt.decode(Core.kt:79)
	at kotlinx.serialization.json.Json.parse(Json.kt:148)
	at com.rogue.state.StateService.loadOrCreateMap(StateService.kt:51)
	at com.rogue.Game.runLevel(Game.kt:51)
	at com.rogue.Game.eventLoop(Game.kt:31)
	at com.rogue.GameKt.main(Game.kt:12)
	at com.rogue.GameKt.main(Game.kt)
```

Если что, пробовал под виндой.

2019-06-18 19:27 UTC, yurii-litvinov commented on README.md
> +В процессе разработке системы предполагается использовать готовые библиотеки взаимодействия с консоль и стандартную библиотеку языка. Таким образом, в границы системы входит -- генератор карт, набор
Как-то подозрительно много опечаток :)

2019-06-18 19:27 UTC, yurii-litvinov commented on README.md
> +[![use-case][Use_case_diagram]][Use_case_diagram_url]
Не, диаграмма случаев использования рисуется относительно пользователей системы, не её внутренних компонентов. Тут она должна получиться очень простой.

2019-06-18 19:27 UTC, yurii-litvinov commented on README.md
> +[![UML][UML_class_diagram]][UML_class_diagram_url]
Для диаграммы классов надо бы какой-нибудь текст, который поясняет, что происходит. Хорошей идеей будет перенести этот текст из Architectural drivers, потому что там помимо требований оказался и рассказ про реализацию, которому там не место. А ещё диаграмма классов должна быть как-то связана с диаграммой компонентов --- должно быть сразу понятно, какой класс к какой компоненте относится. Как диаграмма компонентов появится, проверьте, что это так.

2019-06-18 19:27 UTC, yurii-litvinov commented on README.md
> +
И ещё просили диаграмму последовательностей

2019-06-18 19:27 UTC, yurii-litvinov commented on src/main/kotlin/com/rogue/Game.kt
> +            Thread.sleep(1000)
А оно не умеет это делать как-то асинхронно? Не то чтобы это надо править, просто интересно.

2019-06-18 19:27 UTC, yurii-litvinov commented on src/main/kotlin/com/rogue/actor/Actor.kt
> +    //This is the simplest way to make state serializable.
Сериализация в ущерб объектно-ориентированному дизайну на курсе по архитектуре -- спорное решение :) Но ваше право.

2019-06-18 19:27 UTC, yurii-litvinov commented on src/main/kotlin/com/rogue/actor/WallActor.kt
> +object WallActor {
Вообще, даже таким штукам по-хорошему нужны комментарии

2019-06-18 19:27 UTC, yurii-litvinov commented on src/main/kotlin/com/rogue/draw/Screen.kt
> +    fun init()
К методам интерфейса тоже нужны комментарии, не только к самому интерфейсу

2019-06-18 19:27 UTC, yurii-litvinov commented on src/test/kotlin/com/rogue/map/MapGeneratorTest.kt
> +//    }
Закомментированный код не нужен, Lava Flow же

2019-06-18 19:27 UTC, yurii-litvinov commented on src/test/kotlin/com/rogue/map/LevelMapTest.kt
> +    var map = LevelMap(size, size)
IDEA утверждает, что это паблик-поле :)

2019-06-18 20:37 UTC, akhvorov commented
Поправил замечания по коду. Диздоки немного позже доделаем.
Про падение: у меня тоже такое было, причину не нашел, но удаление и клонирование проекта заново помогло.

2019-06-20 20:20 UTC, AntonCoon commented
Поправили диздок, добавили CI тесты

2019-06-23 19:14 UTC, merged